### ISSUE TITLE
Feature tracker for first release

### ISSUE THREAD

**Issue by izzthedude** [izzthedude/Ignorem#2]
*might keep adding to this list as I go along

## Essential
- [x] Implement gitignore API
- [ ] Implement UI
- [ ] Implement testing
- [ ] General review & cleanup

## Extras
- [ ] Configure pre-commit hooks
- [ ] Automate testing
